[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = "*"
env_logger = "0.9"
log = "0.4"
sqlx = { version = "0.7", features = ["mysql", "runtime-tokio-native-tls"] }
[profile.dev.package.sqlx-macros]
opt-level = 3
